### ISSUE TITLE
Make custom vue plugin

### ISSUE THREAD

**Issue by Hisioni** [Gumball12/vitest-vue-demi-pnpm-monorepo#1]
`packages` > `my-component`,do it's able to wrap as custom vue plugin?

eg:
```ts
import { type App } from vue-demi

const customPlugin = (app: App,  options: Record<string, symbol>) {
   app.component(xxx)
}
```

when monorepo how to fix Vue2.use() and Vue3.use() it's warning Type not adapterable

Thanks for guide

**Comment by Gumball12** [comment]
Thank you for asking a good question. I added [new examples and comments about vue-demi plugin](https://github.com/Gumball12/vitest-vue-demi-pnpm-monorepo/commit/262874192fc62606a235671eb7be7ff3fbab21ea) to the repository. I think it will probably help you.

**Comment by Hisioni** [comment]
Nice! Thank you for guiding me. It helps me a lot~
